apiVersion: v1
kind: Secret
metadata:
  name: snyk-token
type: Opaque
stringData:
  SNYK_TOKEN_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
type: Opaque
stringData:
  GITLAB_TOKEN_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: client-id
type: Opaque
stringData:
  CLIENT_ID_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret
type: Opaque
stringData:
  CLIENT_SECRET_KEY: ""

